version: '3.7'
services:
  linebot:
    env_file: 
      - ./pipeline/.env
    build:
      context: ./pipeline/.
      cache_from:
        - liberator-linebot-python:v1
    pull_policy: always
    image: liberator-linebot-python:v1
    container_name: liberator-linebot-python
    hostname: liberator-linebot-python
    ports:
      - 443:8080
    volumes:
      - ./pipeline/_logs:/usr/src/app/_logs
    restart: always
    networks:
      - Liberator
networks:
    Liberator:
        driver: bridge
